# Generated by Django 5.2.3 on 2025-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_img', models.ImageField(upload_to='')),
                ('b_title', models.TextField()),
                ('b_heading', models.TextField()),
                ('b_blog', models.TextField()),
            ],
        ),
    ]
